### ISSUE TITLE
Does not Automatically Apply Time Configuration on Start

### ISSUE THREAD

**Issue by ab-tools** [tobozo/WiFiManagerTz#5]
Hello tobozo,

cool WiFiManager addition, thanks for that! :-)

Quick question how this is expected to work:
Currently, after restarting it seems to load the preferences correctly, it correctly finds out that NTP is enabled here
https://github.com/tobozo/WiFiManagerTz/blob/master/src/WiFiManagerTz.h#L36
and loads the NTP preferences accordingly.

However, it seems not to automatically apply the time configuration from the preferences at start.
This leads to the preferences correctly filled on the WiFiManager custom web page, but the time not used. I need to go to the time settings webpage after each start and click on "Submit" (without any changes in the form as all correctly prefilled). Only then the time gets actually updated.

Would it not make sense to add a `configTime();` after `NTP::loadPrefs();` here?
https://github.com/tobozo/WiFiManagerTz/blob/master/src/WiFiManagerTz.h#L36

This would immediately apply the saved settings and retrieve an initial time from the NTP server.

Thanks
Andreas

**Comment by tobozo** [comment]
hi, thanks for your feedback :+1: 

`configTime()` triggers a connection, which would come too early when the wifiManager is still waiting for other settings (e.g. first launch), and we don't want that

In the basic example, `WiFiManagerNS::configTime()` is called only [after a wifi connection is established](https://github.com/tobozo/WiFiManagerTz/blob/master/examples/tzupdate/tzupdate.ino#L88)

if you're not using `WifiManager::autoConnect()` feature, I suggest you put the call to `WiFiManagerNS::configTime()` in a conditional block in your setup i.e. when all your network requirements are met and the NTP server is reachable
